#!/bin/bash


#Script para subir archivos locales a un repositorio remoto.

#########################
#      INSTRUCCIONES    #
#########################

# 1- Modificar variables dentro del codigo:

# DEFAULT_REMOTE_DIRECTORY --> un directorio por defecto en tu máquina remota en caso de que 
# no pases uno como argumento
# REMOTE_USER --> el usuario para conectarte remotamente a esa máquina.
# XXX.XXX.X.XXX --> la Ip de tu máquina remota, recomiendo asignarle una Ip estática, sinó no funcionará.
# HOME_DIRECTORY --> el directorio home de tu máquina remota.

# Éste script sube tanto archivos como directorios.

if [ ! $1 ]; then
    echo "Falta decir un archivo o un directorio para subir"
    exit -1
else
    ARG=$1
fi
if [ ! $2 ]; then
    DIR="DEFAULT_REMOTE_DIRECTORY"
else 
    DIR=$2
fi

if [ -f ./$ARG ]; then 
    
    scp $ARG REMOTE_USER@XXX.XXX.X.XXX:$DIR

else
    if [ -d ./$ARG ]; then
        scp -r $ARG REMOTE_USE@XXX.XXX.X.XXX:/HOME_DIRECTORY/$DIR
    else
        echo "No existe ni como archivo ni como directorio"
        exit -1
    fi
    
fi
